only decrypt secrets when needed

diff --git a/commands/secrets/create-registry-key/run b/commands/secrets/create-registry-key/run
--- a/commands/secrets/create-registry-key/run
+++ b/commands/secrets/create-registry-key/run
@@ -2,17 +2,17 @@
 
 if ! kubectl get secret project-registry-key >/dev/null 2>&1
 then
-  if [ -f "$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME/project-registry-service-account.json" ]
+  if [ -f "$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME/project-registry-service-account.json.gpg" ]
   then
-    EMAIL=$(python -c"import json; print (json.load(open("'"'"$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME/project-registry-service-account.json"'"'"))['client_email'])")
+    EMAIL=$(kproject secrets show project-registry-service-account.json | jq --raw-output .client_email)
     kubectl create secret docker-registry project-registry-key \
       --docker-username "_json_key" \
-      --docker-password "$(cat "$PROJECT_ROOT_PATH/private/$ENVIRONMENT_NAME/project-registry-service-account.json")" \
+      --docker-password "$(kproject secrets show project-registry-service-account.json)" \
       --docker-email "$EMAIL" \
       --docker-server "https://$DOCKER_REPO"
     kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "project-registry-key"}]}'
   else
-    echo "private/$ENVIRONMENT_NAME/project-registry-service-account.json not found" 1>&2
+    echo "private/$ENVIRONMENT_NAME/project-registry-service-account.json.gpg not found" 1>&2
     exit 1
   fi
 fi
